# Generated by Django 5.0.2 on 2024-03-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_alter_page_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
