# Generated by Django 5.0.2 on 2024-03-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0006_alter_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
